### ISSUE TITLE
tarball missing util.py

### ISSUE THREAD

**Issue by idella** [tavendo/txaio#3]
The tarball uploaded to pypi is missing the file 
https://github.com/tavendo/txaio/blob/master/test/util.py
rendering the testsuite unusable. Please add. 
Minor tip form #python.  Try inhouse use of
https://github.com/mgedmin/check-manifest/
to assist in picking up lost or missed files. I have never done an uploading process to pypi myself.

**Comment by Jenselme** [comment]
:+1:
