### ISSUE TITLE
README.rst not found during pip install

### ISSUE THREAD

**Issue by seanroark** [tavendo/txaio#32]
This is breaking pip install autobahn as well

Tag 2.02
Windows 10
Python 3.5.0

Work around: installing from source works fine, which makes it non-obvious how to fix this.

Problem:
PS C:\Users\[user]\dev\autobahn> pip install txaio
Collecting txaio
  Using cached txaio-2.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\[user]\AppData\Local\Temp\pip-build-7zimen6i\txaio\setup.py", line 40, in <module>
        with open('README.rst') as f:
    OSError: [Errno 22] Invalid argument: 'README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\[user]\AppData\Local\Temp\pip-build-7zimen6i\txaio

Oddly, pip install -e works fine:
PS C:\Users\[user]\dev\txaio> pip install -e .
Obtaining file:///C:/Users/[user]/dev/txaio
Requirement already satisfied (use --upgrade to upgrade): six in c:\program files\python 3.5\lib\site-packages\six-1.10.
0-py3.5.egg (from txaio==2.0.2)
Installing collected packages: txaio
  Running setup.py develop for txaio
Successfully installed txaio

**Comment by meejah** [comment]
Thanks for the report!
I also added a packaging-test so we can't make a broken package in the future.

@oberstet I bumped the version too, so should be able to do a release of this immediately.

**Comment by oberstet** [comment]
@meejah thx for arranging things so I can proceed with minimal efforts;) https://pypi.python.org/pypi/txaio/2.0.3

a minor thing: the pypi "readme" doesnt look that pretty compared to https://github.com/tavendo/txaio#txaio .. not a big thing, maybe next release ..

**Comment by oberstet** [comment]
AB Py / pypi readme: I think I recently fixed this https://pypi.python.org/pypi/autobahn .. already forgot again what I did exactly ..
