### ISSUE TITLE
New logging

### ISSUE THREAD

**Issue by oberstet** [tavendo/txaio#8]
A logging shim for Twisted and asyncio logging facilities that allows us to write single-source logging code in AutobahnPython

**Comment by meejah** [comment]
I'd guess this should include dealing with ``.message`` vs ``.args`` sorts of issues, similar to https://github.com/tavendo/AutobahnPython/issues/484

**Comment by oberstet** [comment]
That would be could to factor out in txaio, yes. Log a Twisted failure with all these guards, so we don't have to add that code everywhere

**Comment by meejah** [comment]
Okay, so the idioms for logging and formatting ``IFailedFuture`` instances are:

```python
class Foo(object):
    log = txaio.make_logger()

    def connect(self):
        try:
            self.log.info("Connecting")
            raise Exception("an error")
        except:
            fail = txaio.create_failure()
            self.log.error("Connection failed: {msg}", msg=txaio.failure_message(fail))
            self.log.debug("{traceback}", traceback=txaio.failure_format_traceback(fail))
            # Exception instance in fail.value
```

**Comment by oberstet** [comment]
Cool! That looks good.

Ah, we could also collect hints like this in the Dev.md

Am 17.09.2015 3:28 vorm. schrieb meejah <notifications@github.com>:

Okay, so the idioms for logging and formatting IFailedFuture instances are:

class Foo(object):
    log = txaio.make_logger()

    def connect(self):
        try:
            self.log.info("Connecting")
            raise Exception("an error")
        except:
            fail = txaio.create_failure()
            self.log.error("Connection failed: {msg}", msg=txaio.failure_message(fail))
            self.log.debug("{traceback}", traceback=txaio.failure_format_traceback(fail))
            # Exception instance in fail.value

**Comment by meejah** [comment]
https://github.com/tavendo/AutobahnPython/pull/513

**Comment by oberstet** [comment]
ok, this is in trunk now
