### ISSUE TITLE
Clean up Failure handling

### ISSUE THREAD

**Issue by meejah** [tavendo/txaio#9]
In order to be more future-proof and clean up the IFailuedFuture interface we will:

- get rid of everything except ``.value`` from the interface
- provide ``txaio.failure_message(failure)`` which returns a unicode
- provide ``txaio.failure_traceback(failure)`` which returns a traceback object

**Comment by oberstet** [comment]
For the record, we've had an extensive discussion about this on slack, above is the result, and I think it's very reasonable. +1

**Comment by meejah** [comment]
I also made ``txaio.failure_format_traceback(failure)`` which returns a string (the formatted traceback) for convenience.
